# github Alacritty Colors

# Default colors
[colors.primary]
# background = '#ffffff'
# foreground = '#0E1116'
background = '0xffffff'
foreground = '0x24292f'

# Normal colors
[colors.normal]
black     = '0x24292e'
red       = '0xd73a49'
green     = '0x28a745'
yellow    = '0xdbab09'
blue      = '0x0366d6'
magenta   = '0x5a32a3'
cyan      = '0x0598bc'
white     = '0x6a737d'

# black   = '#24292f'
# red     = '#cf222e'
# green   = '#116329'
# yellow  = '#4d2d00'
# blue    = '#0969da'
# magenta = '#8250df'
# cyan    = '#1b7c83'
# white   = '#6e7781'

# Bright colors
[colors.bright]
black   = '0x959da5'
red     = '0xcb2431'
green   = '0x22863a'
yellow  = '0xb08800'
blue    = '0x005cc5'
magenta = '0x5a32a3'
cyan    = '0x3192aa'
white   = '0xd1d5da'

# black   = '#57606a'
# red     = '#a40e26'
# green   = '#1a7f37'
# yellow  = '#633c01'
# blue    = '#218bff'
# magenta = '#a475f9'
# cyan    = '#3192aa'
# white   = '#8c959f'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#a40e26'
